Lee-JoungHyun/BOJ_14889.java, Lee-JoungHyun/BOJ_1759.java
=> 이중현 / 2월 26일 / 2문제

enduf768640/BOJ_12865.java, enduf768640/BOJ_2579.java
=> 김두열 / 2월 28일 / 2문제

swLeesw/BOJ_12865.java, swLeesw/BOJ_2579.java
=> 이승원 / 2월 28일 / 2문제

monam2/BOJ_2579.java
생각하는데에 시간을 너무 많이 써서 한 문제밖에 못 풀었습니다ㅠ
=> 강창우 / 2월 28일 / 1문제

wonxxikim/BOJ_2470.java
=> 김지원 / 2월 29일 / 1문제

monam2/BOJ_2110.java, monam2/BOJ_2470.java
두 용액
- 해결 못해서 이분탐색 이용한 답을 찾아봤으나 이해 못함. 투포인터로 해결
=> 강창우 / 2월 29일 / 2문제

MJ-Kor/BOJ_2110.java, MJ-Kor/BOJ_2470.java
=> 김민주 / 2월 29일 / 2문제

enduf768640/BOJ_1644.java, enduf768640/BOJ_2531.java
=> 김두열 / 3월 1일 / 2문제

wonxxikim/BOJ_1644.java, wonxxikim/BOJ_2531.java
소수의 연속합(1644)에서 시간초과가 발생하여 에라토스테네스의 채 코드참고
=> 김지원 / 3월 1일 / 2문제

JAEKWANG97/BOJ_1644.java, JAEKWANG97/BOJ_2110.java, JAEKWANG97/BOJ_2531.java
0301 문제 2개 + 이전에 못 풀었던 공유기 설치 문제 해결 완료.
=> 유재광 / 3월 1일 / 3문제

monam2/BOJ_1644.java, monam2/BOJ_2531.java
소수의 연속합
- 해결 못해서 정답 참고. left, right 포인터를 소수 리스트 양 끝에 두는 것만 생각함.
=> 강창우 / 3월 1일 / 2문제

inhohyun/BOJ_1644.java, inhohyun/BOJ_2531.java
실제 개발을 하면서도 static 보단 매개변수를 활용하는 편이 좋은가요? 
아니면 유지보수가 편하기 위해? 등을 위해 static을 활용하시는 편이신가요?
=> 인호현 / 3월 1일 / 2문제

monam2/SEA_4014.java
1번 해결 못해서 정답 코드 보면서 공부했습니다
2번까진 도저히.. 못풀겠습니다... ㅠㅠ...
=> 강창우 / 3월 2일 / 1문제

cshyun7097/SEA_4014.java
1949번 : 접근 방법을 생각했으나 시작점을 잡는 로직에서 막힘.
=> 최승현 / 3월 2일 / 1문제

wonxxikim/SWEA_4014.java
=> 김지원 / 3월 2일 / 1문제

cshyun7097/SEA_1949.java
=> 최승현 / 3월 3일 / 1문제

mmalfoy/BOJ_1949.java, mmalfoy/BOJ_4014.java
=> 김대영 / 3월 2일 / 2문제

monam2/SEA_1949.java
=> 강창우 / 3월 3일 / 1문제

enduf768640/BOJ_11657.java, enduf768640/BOJ_18352.java
=> 김두열 / 3월 5일 / 2문제

wonxxikim/BOJ_1657.java, wonxxikim/BOJ_18352.java
1657 , 벨만포드 알고리즘을 몰라서 참고하여 풀이했습니다.
=> 김지원 / 3월 5일 / 2문제

cshyun7097/BOJ_11657.java, cshyun7097/BOJ_18352.java
11657번은 벨만 포드 문제로 아직 어려워서 풀다가 해답을 보고 작성하였습니다.
=> 최승현 / 3월 5일 / 2문제

inhohyun/BOJ_11657.java, inhohyun/BOJ_18352.java
벨만 포드 알고리즘을 몰라 다른 사람 코드를 보며 학습했습니다..
=> 인호현 / 3월 5일 / 2문제

JAEKWANG97/BOJ_11657.java, JAEKWANG97/BOJ_18352.java
타임머신의 경우 벨만포드 유형을 처음 봐서 해당 알고리즘 공부 후 벨만포드 틀에 맞춰서 하였습니다.
=> 유재광 / 3월 5일 / 2문제

monam2/BOJ_11657.java, monam2/BOJ_18352
타임머신
- 벨만포드 알고리즘를 처음 접해서 정답 코드를 보며 공부했습니다. 백준 제출은 하지 않아서, 다음에 다시 풀어보겠습니다.
=> 강창우 / 3월 5일 / 2문제

JAEKWANG97/BOJ_1647.java, JAEKWANG97/BOJ_1976.java
=> 유재광 / 3월 6일 / 2문제

enduf768640/BOJ_1647.java, enduf768640/BOJ_1976.java
<여행 가자> 문제 처음에 DFS로 풀었는데 서로소 집합(Union-Find) 으로도 풀어봤습니다.
```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.StringTokenizer;
public class BOJ_1976 {
private static BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
private static StringTokenizer st;
private static int N;
private static int M;
private static Node[] tourSpots;
private static boolean[][] graph;
private static int[] travelOrder;
private static boolean canGo = true;
public static void main(String[] args) throws IOException {
init();
makeRoute();
travel();
printAnswer();
}
private static void makeRoute() {
for (int i = 1; i <= N; i++) {
for (int j = 1; j <= N; j++) {
if (graph[i][j]) {
union(tourSpots[i], …
```
=> 김두열 / 3월 6일 / 2문제

enduf768640/BOJ_10844.java, enduf768640/BOJ_1107.java
=> 김두열 / 3월 7일 / 2문제

eunsung/BOJ_10844.java, eunsung/BOJ_1107.java
=> 최은성 / 3월 7일 / 1문제

monam2/BOJ_10844.java
리모컨
- 조금만 더 시도하면 풀릴 것 같아서 내일이나 주말에 다시 시도해보겠습니다.
=> 강창우 / 3월 7일 / 1문제

mmalfoy/PGS_150368.java, mmalfoy/PGS_42840.java, mmalfoy/PGS_42891.java, mmalfoy/PGS_67259.java
=> 김대영 / 3월 9일 / 3문제

hyeonhakyi/PGS_150368.java, hyeonhakyi/PGS_42891.java, hyeonhakyi/PGS_67259.java, hyeonhakyi/PSG_12980.java
=> 이학현 / 3월 9일 / 4문제

Lee-JoungHyun/PRO_12980.java, Lee-JoungHyun/PRO_150368.java, Lee-JoungHyun/PRO_42891.java, Lee-JoungHyun/PRO_67259.java
무지의 먹방 라이브는 효율성을 통과하지 못해서 답을 참고했습니다...
=> 이중현 / 3월 9일 / 4문제

JiHunparkkk/PGS_12980.java, JiHunparkkk/PGS_150368.java, JiHunparkkk/PGS_42891.java, JiHunparkkk/PGS_67259.java
'무지의 먹방 라이브' 문제는 시간 복잡도를 생각하기 어려워 블로그와 영상을 참고하였습니다.
https://moonsbeen.tistory.com/371
=> 박지훈 / 3월 9일 / 4문제

cshyun7097/PGS_12980.java, cshyun7097/PGS_150368.java, cshyun7097/PGS_67259.java
경주로 건설 70분 걸렸습니다 + visited부분에서 해답보고 이해했습니다.
무지의 먹방 라이브는 아직 풀지 못했습니다...
=> 최승현 / 3월 9일 / 3문제

inhohyun/BOJ_2573.java, inhohyun/BOJ_5052.java, inhohyun/PGS_42891.java, inhohyun/PGS_67259.java
경주로 건설,  무지의 먹방 라이브는 답지를 참고했습니다..
=> 인호현/ 3월 11일 / 4문제

eunsung/BOJ_2573.java, eunsung/BOJ_5052.java
=> 최은성 / 3월 11일 / 2문제

chchaeun/BOJ_16928.java, chchaeun/BOJ_4179.java
- 처음에 DP로 접근하려고 했는데 실패
- 한 방향으로 진행되는 게 아니라 뒤로 돌아가야 되는 부분 때문에 DP로 풀면 복잡함
- BFS로 접근해서 풀이
- 메모리 초과, 시간 초과로 삽질...
- 불이 시간대 별로 얼마나 퍼지는지 먼저 표시하고 지훈이를 움직이는 방식으로
=> 김채은 / 3월 12일 / 2문제

inhohyun/BOJ_16928.java, inhohyun/BOJ_4179.java
불! 문제가 61%에서 반례가 있는데 잡지 못했습니다...내일 수정하겠습니다.
=> 인호현 / 3월 13일 / 2문제

monam2/BOJ_16928.java
불!
- 해결이 잘 안돼서 이번주 내에 다시 풀어보겠습니다 ㅠ
=> 강창우 / 3월 12일 / 1문제

JAEKWANG97/BOJ_1038.java, JAEKWANG97/BOJ_2251.java
=> 유재광 / 3월 13일 / 2문제

inhohyun/BOJ_2011.java
암호 코드를 풀던 중 시간이 없어 답안지를 참조했습니다..
오늘 본가에 갈 일이 생겨 마무리하지 못해 내일 문제에 추가해서 올리도록 하겠습니다.
=> 인호현 / 3월 15일 / 1문제

wonxxikim/BOJ_2011.java
암호코드 : dp로 풀었지만 40%에서 계속 틀려 코드 참고하였음.
오늘 관통 프로젝트로 인하여 1문제만 풀었습니당...........
=> 김지원 / 3월 16일 / 1문제

chchaeun/BOJ_5972.java
=> 김채은 / 3월 15일 / 1문제

JiHunparkkk/BOJ_2011.java
1. 암호코드 
- dp로 접근하였으나, 정답을 찾지 못하여 정답을 봤습니다.
2번 문제는 관통프로젝트와 다른 스터디활동으로 풀지 못하였습니다. 
내일까지 풀도록 하겠습니다.
=> 박지훈 / 3월 15일 / 1문제

Lee-JoungHyun/BOJ_2011.java, Lee-JoungHyun/BOJ_5972.java
암호코드를 dp의 방식으로 풀었는데
예외처리가 부족한것 같아 통과하지 못했습니다
=> 이중현 / 3월 15일 / 1문제

zzun73/BOJ_2011.java
=> 남혁준 / 3월 15일 / 1문제

JAEKWANG97/PGS_118668.java, JAEKWANG97/PGS_17678.java, JAEKWANG97/PGS_92341.java, JAEKWANG97/PGS_92342.java
토요일 B형 일정과 월요일 과목 평가로 인해 시간을 많이 할애할 수 없어서, 문제 당 60분 초과 후 블로그 참고했습니다.
=> 유재광 / 3월 16일 / 4문제

cshyun7097/PGS_무지의_먹방_라이브.java, cshyun7097/PGS_주차_요금_계산.java, cshyun7097/PGS_코딩_테스트_공부.java
2문제는 풀지 못했습니다. 내일 문제와 같이 올리도록 하겠습니다!
=> 최승현 / 3월 16일 / 3문제

zzun73/PGS_92341.java
=> 남혁준 / 3월 16일 / 1문제

enduf768640/BOJ_2011.java, enduf768640/BOJ_5972.java
B형 시험이랑 자소서 때문에 프로그래머스 문제를 못풀었습니다 😥
이번 주에 틈틈히 풀어서 제출하겠습니다!
=> 김두열 / 3월 16일 / 2문제

zzun73/BOJ_11060.java, zzun73/BOJ_15683.java, zzun73/PGS_118668.java, zzun73/PGS_17678.java, zzun73/PGS_92342.java
=> 남혁준 / 3월 18일 / 5문제

Lee-JoungHyun/BOJ_11060.java, Lee-JoungHyun/BOJ_15683.java, Lee-JoungHyun/PGS_92341.java, Lee-JoungHyun/PGS_92342.java
=> 이중현 / 3월 18일 / 2문제

mmalfoy/BOJ_11060.java
금일 과제 제출에 시간이 오래걸려, 1문제를 못풀었습니다.. 
내일 PR에 추가하여 제출하겠습니다.
=> 김대영 / 3월 18일 / 1문제

cshyun7097/BOJ_11060.java, cshyun7097/BOJ_15683.java
토요일 과제는 아직 풀지 못해서 푸는데로 바로 추가해서 pr하겠습니다
=> 최승현 / 3월 18일 / 2문제

inhohyun/BOJ_9205.java
테트로미노 문제를 못풀었습니다..내일 중으로 풀어서 올리겠습니다.
=> 인호현 / 3월 19일 / 1문제

mmalfoy/BOJ_14500.java, mmalfoy/BOJ_15683.java, mmalfoy/BOJ_9205.java
=> 김대영 / 3월 19일 / 3문제

JiHunparkkk/BOJ_14499.java, JiHunparkkk/BOJ_21608.java
[14499 - 주사위 굴리기] - 아이디어가 떠오르질 않아 문제 해설만 보았습니다.
=> 박지훈 / 3월 20일 / 2문제

MJ-Kor/BOJ_21608.java
싸피 백엔드 학습으로 시간상 1문제 풀이만 진행하였습니다.
=> 김민주 / 3월 20일 / 1문제

zzun73/BOJ_14499.java, zzun73/BOJ_21608.java
상어초등학교 오답 해결하고 오늘 문제와 함께 올리겠습니다
=> 남혁준 / 3월 20일 / 1문제

JAEKWANG97/BOJ_14499.java, JAEKWANG97/BOJ_21608.java
=> 유재광 / 3월 20일 / 2문제

hyeonhakyi/BOJ_16234.java
관통 프로젝트 대비 백엔드 과제 때문에 1문제를 못 풀었습니다 내일부터 주말 안으로 풀겠습니다. 죄송합니다.
=> 이학현 / 3월 21일 / 1문제

mmalfoy/BOJ_16234.java
과제로 인해 시간이 부족하여, 내일 1문제 추가하여 PR하겠습니다.
=> 김대영 / 3월 21일 / 1문제

JaeHunJang/BOJ_20056.java
=> 장재훈 / 3월 21일 / 1문제

MJ-Kor/BOJ_16234.java
백엔드 관통프로젝트 준비로 인해 2문제 모두 진행할 시간이 부족했습니다.
=> 김민주 / 3월 21일 / 1문제

cshyun7097/BOJ_16234.java
과제로 인해 1문제를 풀지 못했습니다. 주말내에 풀어서 올리겠습니다!
=> 최승현 / 3월 21일 / 1문제

JiHunparkkk/BOJ_16234.java
=> 박지훈 / 3월 21일 / 1문제

wonxxikim/BOJ_17144.java
=> 김지원 / 3월 22일 / 1문제

chchaeun/PG_17678.py, chchaeun/PG_92341.py, chchaeun/PG_92342.py
=> 김채은 / 3월 22일 / 3문제

JiHunparkkk/BOJ_17144.java, JiHunparkkk/BOJ_3190.java
3/21 (목), 못 푼 문제는 주말동안 해결 해보겠습니다.
=> 박지훈 / 3월 22일 / 2문제

zzun73/BOJ_3190.java
=> 남혁준 / 3월 22일 / 1문제

hyeonhakyi/BOJ_17144.java
=> 이학현 / 3월 22일 / 1문제

cshyun7097/BOJ_3190.java
관통프로젝트로 인해 1문제밖에 풀지못했습니다. 주말 내로 풀어올리겠습니다.
=> 최승현 / 3월 22일 / 1문제

JAEKWANG97/BOJ_3190.java
=> 유재광 / 3월 22일 / 1문제

mmalfoy/BOJ_17144.java, mmalfoy/BOJ_20056.java, mmalfoy/BOJ_3190.java
=> 김대영 / 3월 22일 / 3문제

BOJ_3190.java
백엔드 관통 프로젝트로 인해 1문제 밖에 해결 못하였습니다.
=> 김민주 / 3월 22일 / 1문제

Lee-JoungHyun/BOJ_3190.java
=> 이중현 / 3월 22일 / 1문제

wonxxikim/BOJ_3190.java
=> 김지원 / 3월 22일 / 2문제

JAEKWANG97/CT_1.java, JAEKWANG97/CT_2.java
=> 유재광 / 3월 23일 / 2문제

inhohyun/CT_1.java
포탑 부수기 - 풀다가 중도 포기(솔루션을 떠올리지 못함)
토끼와 경주 - 못품..
더 시간 투자를 하고 싶었으나 월말평가 준비로 인해 더 도전하지 못했습니다..
=> 인호현 / 3월 24일 / 1문제

mmalfoy/CT_2.java
월말평가 준비로 시간이 부족하여 다 못풀었습니다..
토끼와 경주는 2번째 테케에서 계속 시간 초과가 발생하여 고민중에 있습니다.
=> 김대영 / 3월 24일 / 1문제

hyeonhakyi/BOJ_13549.java, hyeonhakyi/BOJ_20057.java
=> 이학현 / 3월 25일 / 2문제

mmalfoy/BOJ_13549.java
자소서 작성으로 인한 시간상 제약으로 1문제 PR합니다 ..
=> 김대영 / 3월 25일 / 1문제

inhohyun/BOJ_13549.java, inhohyun/BOJ_20057.java
=> 인호현 / 3월 26일 / 2문제

JiHunparkkk/BOJ_13549.java
26일(화) 까지 필요한 자소서 작성으로 1문제만 풀었습니다...
=> 박지훈 / 3월 26일 / 1문제

MJ-Kor/BOJ_13549.java
싸피 월말평가 연관 과제로 인해 1문제만 제출하겠습니다.
=> 김민주 / 3월 25일 / 1문제

zzun73/BOJ_13549.java, zzun73/BOJ_20057.java
=> 남혁준 / 3월 25일 / 2문제

JAEKWANG97/BOJ_13549.java, JAEKWANG97/BOJ_20057.java
=> 유재광 / 3월 25일 / 2문제

monam2/BOJ_11052.java, monam2/BOJ_17471.java
못 푼 문제들은 이번 주말 내로 모두 제출하겠습니다..
=> 강창우 / 3월 27일 / 2문제

hyeonhakyi/BOJ_2212.java, hyeonhakyi/BOJ_3020.java
=> 이학현 / 3월 29일 / 2문제

MJ-Kor/Main_3020_김민주.java
=> 김민주 / 3월 29일 / 1문제

inhohyun/BOJ_2212.java, inhohyun/BOJ_3020.java
=> 인호현 / 3월 29일 / 2문제

chchaeun/메이즈러너.py, chchaeun/포탑부수기.py
=> 김채은 / 3월 30일 / 2문제

JAEKWANG97/BOJ_2212.java, JAEKWANG97/BOJ_3020.java, JAEKWANG97/CT_3
메이즈러너는 해설 참고하였고, 나머지 한 문제는 잘 모르겠습니다. 아직 실력이 부족한 것 같습니다.
=> 유재광 / 3월 30일 / 3문제

hellomatia/CT_메이즈러너.java, hellomatia/CT_코드트리채점기.java
=> 이지표 / 3월 31일 / 2문제

JaeHunJang/CT_메이즈러너.java
메이즈 러너 문제는 풀이 실패했습니다.
코드트리 채점기 문제는 풀이 못했습니다..
=> 장재훈 / 3월 30일 / 1문제

inhohyun/CT_메이즈러너.java
메이즈 러너 해설을 많이 참조했습니다..2번까지 풀고싶었지만 실패했습니다..
=> 인호현 / 3월 31일 / 1문제

cshyun7097/메이즈러너.java
=> 최승현 / 3월 31일 / 0문제

inhohyun/BOJ_2660.java
=> 인호현 / 4월 1일 / 1문제

mmalfoy/BOJ_21609.java, mmalfoy/BOJ_2660.java, mmalfoy/CT_메이즈러너.java, mmalfoy/CT_코드트리채점기.java
=> 김대영 / 4월 1일 / 4문제

hyeonhakyi/BOJ_21609.java, hyeonhakyi/BOJ_2660.java
=> 이학현 / 4월 1일 / 1문제

cshyun7097/BOJ_2660.java
상어 중학교는 거의 다 구현했지만 아직 풀지 못했습니다. 내일 완료해서 올리겠습니다.
=> 최승현 / 4월 1일 / 1문제

zzun73/BOJ_2660.java
21609 문제는 금일 문제와 함께 PR 하겠습니다,,
=> 남혁준 / 4월 1일 / 1문제

JAEKWANG97/BOJ_17070.java, JAEKWANG97/BOJ_2294.java
=> 유재광 / 4월 3일 / 2문제

inhohyun/BOJ_2458.java
=> 인호현 / 4월 5일 / 1문제

Lee-JoungHyun/BOJ_2458.java
개인적인 일정이 있어서 1문제밖에 풀지 못했습니다
주말에 같이 올리겠습니다
=> 이중현 / 4월 5일 / 1문제

JaeHunJang/BOJ_8983.java
개인 사정으로 인해 1문제 밖에 풀이를 못했습니다.
내일 마저 풀어서 제출하겠습니다.
=> 장재훈 / 4월 5일 / 1문제

JiHunparkkk/BOJ_2458.java
사냥꾼 (8983) 문제는 부분 정답으로 9점 맞았습니다.
오늘 일정이 있어서 내일 다시 풀어보겠습니다!
=> 박지훈 / 4월 5일 / 1문제

monam2/BOJ_2458.java, monam2/BOJ_8983.java
사냥꾼 문제는 주말에 이분탐색으로 다시 풀어보겠습니다.
=> 강창우 / 4월 5일 / 2문제

MJ-Kor/BOJ_2458.java
알고리즘 관통 프로젝트 보완으로 인해 1문제만 풀이하였습니다.
=> 김민주 / 4월 5일 / 1문제

JAEKWANG97/BOJ_2458.java
나머지 한 문제 못 풀었습니다. 금일 제출 하겠습니다.
=> 유재광 / 4월 5일 / 1문제

JaeHunJang/BOJ_2458.java, JaeHunJang/CT_왕실의기사대결.java
어제 미제출 문제 제출합니다.
4월 6일 문제는 풀이 실패했습니다..
=> 장재훈 / 4월 6일 / 2문제

JAEKWANG97/BOJ_8983.java, JAEKWANG97/CT_왕실의기사대결.java
=> 유재광 / 4월 5일 / 2문제

hyeonhakyi/CT_왕실의기사대결.java
문제가 어려워 답을 참고 하였고 나머지 한 문제는 어려워서 풀지 못했습니다.
=> 이학현 / 4월 7일 / 1문제

mmalfoy/CT_왕실의기사대결.java
문제 답안 참고하여 제출합니다.
남은 한문제는 마저 푸는대로 PR하겠습니다 ..
=> 김대영 / 4월 7일 / 1문제

JiHunparkkk/BOJ_8983.java
- 금요일 못 푼 문제 제출합니다.
- 주말 문제는 풀지 못하였습니다..
=> 박지훈 / 4월 7일 / 1문제

cshyun7097/CT_왕실의기사대결.java
몸이 좋지 않아 2시간 정도 공부하다가 답지보고 풀었습니다.
나머지 한문제는 어려워서 풀지 못했습니다.
=> 최승현 / 4월 7일 / 1문제

inhohyun/CT_왕실의기사대결.java
1번은 중간에 답안지를 참조했습니다..
2번은 풀지 못했습니다.
=> 인호현 / 4월 7일 / 1문제

MJ-Kor/BOJ_1699.java, MJ-Kor/BOJ_8983.java, MJ-Kor/BOJ_9465.java
=> 김민주 / 4월 8일 / 3문제

mmalfoy/BOJ_1699.java, mmalfoy/BOJ_9465.java
=> 김대영 / 4월 8일 / 2문제

monam2/BOJ_20055.java
=> 강창우 / 4월 9일 / 1문제

mmalfoy/BOJ_20055.java
남은 1문제는 답안 확인하여 디버깅 중에 있습니다.
마저 풀어 내일 PR하겠습니다..
=> 김대영 / 4월 10일 / 1문제

cshyun7097/BOJ_20055.java
한문제는 아직 풀지 못했습니다. 이번주 내로 올리겠습니다.
=> 최승현 / 4월 9일 / 1문제

mmalfoy/BOJ_2156.java, mmalfoy/BOJ_2225.java, mmalfoy/BOJ_9935.java
=> 김대영 / 4월 10일 / 3문제

inhohyun/BOJ_1041.java, inhohyun/BOJ_11051.java
=> 인호현/ 4월 11일 / 2문제

zzun73/BOJ_2343.java, zzun73/BOJ_2665.java
=> 남혁준 / 4월 12일 / 2문제

minggwen/BOJ_Main_2343.java
개인 일정상 나머지 한 문제는 토요일까지 제출하겠습니다
=> 신민경 / 4월12일 / 1문제

JAEKWANG97/BOJ_1890.java, JAEKWANG97/BOJ_2175.java, JAEKWANG97/BOJ_2343.java, JAEKWANG97/BOJ_2665.java
4월 12일 제출 못했던 문제까지 총 4문제 제출합니다.
=> 유재광 / 4월 13일 / 4문제

mmalfoy/BOJ_1890.java, mmalfoy/BOJ_21758.java, mmalfoy/BOJ_2343.java, mmalfoy/BOJ_2665.java
=> 김대영 / 4월 13일 / 4문제

hyeonhakyi/BOJ_1744.java, hyeonhakyi/BOJ_7662.java
=> 이학현 / 4월 15일 / 2문제 

enduf768640/BOJ_1253.java
=> 김두열 / 4월 16일 / 1문제

JiHunparkkk/BOJ_1253.java
=> 박지훈 / 4월 16일 / 1문제

BOJ_7662.java, BOJ_9465.java, MJ-Kor/BOJ_1253.java
=> 김민주 / 4월 16일 / 3문제

inhohyun/BOJ_2211.java
=> 인호현 / 4월 17일 / 1문제

JAEKWANG97/BOJ_13701.java, JAEKWANG97/BOJ_2211.java
- **축** 중복제거 java 전체 2등 달성 **하**
=> 유재광 / 4월 17일 / 2문제

zzun73/BOJ_13701.java, zzun73/BOJ_2211.java
=> 남혁준 / 4월 17일 / 2문제

minggwen/PGS_72412.java
다음주 과목평가 알고리즘 준비로
1문제만 풀어 제출합니다ㅠㅠ
=> 신민경 / 4월 18일 / 1문제

enduf768640/PGS_150369.java
=> 김두열 / 4월 18일 / 1문제

inhohyun/PGS_72412/java
=> 인호현 / 4월 18일 / 1문제

hyeonhakyi/PSG_150369.java
=> 이학현 / 4월 18일 / 1문제

JiHunparkkk/BOJ_2211.java, JiHunparkkk/PGS_150369.java, JiHunparkkk/PGS_72412.java
- 4월 17(수) 문제 추가
- 금일 문제 (순위검색) 효율성 실패 -> 블로그 참조
=> 박지훈 / 4월 18일 / 3문제

cshyun7097/PGS_순위검색
한문제밖에 풀지 못했습니다. 다음에 같이 풀어서 제출하겠습니다
=> 최승현 / 4월 18일 / 1문제

zzun73/PGS_72412.java
=> 남혁준 / 4월 18일 / 1문제

hyeonhakyi/PGS_17677.java
=> 이학현 / 4월 19일 / 1문제

JAEKWANG97/PGS_150369.java, JAEKWANG97/PGS_72412.java
=> 유재광 / 4월 19일 / 2문제

hyeonhakyi/PGS_17684.java
=> 이학현 / 4월 20일 / 1문제

JAEKWANG97/PGS_17677.java, JAEKWANG97/PGS_17679.java, JAEKWANG97/PGS_17684_java, JAEKWANG97/PGS_17686.java
- 뉴스 클러스터링
- 프렌즈4블록
- 파일명 정렬
- 압축
=> 유재광 / 4월 22일 / 4문제

JAEKWANG97/PGS_17681.java, JAEKWANG97/PGS_17683.java
=> 유재광 / 4월 23일 / 2문제

hyeonhakyi/PGS_17681.java, hyeonhakyi/PGS_17683.java
=> 이학현 / 4월 23일 / 2문제 

hyeonhakyi/PGS_42890.java, hyeonhakyi/PGS_42892.java
=> 이학현 / 4월 24일 / 2문제

minggwen/PGS_17686.java
이번주만 스프링 과제 & 월말평가 준비로 한 문제씩만 제출하겠습니다 🥲
=> 신민경 / 4월 24일 / 1문제

hellomatia/PGS_42890.java, hellomatia/PGS_42892.java
=> 이지표 / 4월 24일 / 2문제

wonxxikim/PGS_17681.java
-비밀지도 : 블로그 참고
- 내일 아침 1문제 더 PR 예정
=> 김지원 / 4월 24일 / 1문제

JiHunparkkk/PGS_42890.java
- 스프링 공부와 함께 병행하다가 시간 부족으로 1문제만 풀이하였습니다.
=> 박지훈 / 4월 24일 / 1문제

zzun73/PGS_42890.java, zzun73/PGS_42892.java
=> 남혁준 / 4월 24일 / 2문제

hellomatia/PGS_42889.java
=> 이지표 / 4월 25일 / 1문제

JiHunparkkk/PGS_42889.java
=> 박지훈 / 4월 25일 / 1문제

cshyun7097/PGS_실패율.java
관통프로젝트 준비로 1문제밖에 풀지 못했습니다.
내일 한문제 추가해서 올리겠습니다.
=> 최승현 / 4월 25일 / 1문제

minggwen/PGS_42889.java
이번주는 스프링 월말평가 + 관통 준비로 한 문제씩 제출하겠습니다!
=> 신민경 / 4월 25일 / 1문제

minggwen/PGS_1835.java, minggwen/PGS_60059.java
금요일 1문제 토요일 1문제
이번주는 월말평가 스프링 준비로 한 문제씩 제출하겠습니다.
=> 신민경 / 4월 27일 / 1문제

JAEKWANG97/PGS_42888.javaq, JAEKWANG97/PGS_42889.java, JAEKWANG97/PGS_60059.java, JAEKWANG97/PGS_60062.java
=> 유재광 / 4월 26일 / 4문제

zzun73/PGS_1835.java, zzun73/PGS_60059.java
블로그 참고하였습니다. 월요일 시험준비로 1문제씩만 제출합니다.
=> 남혁준 / 4월 27일 / 2문제

Lee-JoungHyun/PGS_1836.java, Lee-JoungHyun/PGS_1853.java, Lee-JoungHyun/PGS_60059.java, Lee-JoungHyun/PGS_60062.java
=> 이중현 / 4월 27일 / 4문제

hellomatia/PGS_1835.java
=> 이지표 / 4월 28일 / 1문제

inhohyun/PGS_1835.java
1번문제 풀다가 더 시간투자하기 어려워 답안지를 참고했습니다..
월요일 과목/월말평가 대비로 1문제만 풀어봤습니다.
=> 인호현 / 4월 28일 / 1문제

cshyun7097/PGS_오픈채팅팡
이번주 과목평가와 월말평가가 동시에 있어 모두 풀지 못했습니다.
이번주내로 못푼문제 올리겠습니다.
=> 최승현 / 4월 28일 / 1문제

hellomatia/PGS_92334.java
=> 이지표 / 4월 29일 / 1문제

MJ-Kor/PGS_92334.java
정보처리기사 준비 및 개인 공부로 1문제만 풀이하였습니다.
=> 김민주 / 4월 29일 / 1문제

hellomatia/PGS_72411.java, hellomatia/PGS_72414.java
=> 이지표 / 4월 30일 / 2문제

JaeHunJang/PGS_72411.java
=> 장재훈 / 4월 30일 / 1문제

hyeonhakyi/PGS_72411.java, hyeonhakyi/PGS_72414.java
=> 이학현 / 4월 30일 / 2문제 

JiHunparkkk/PGS_72411.java
- 메뉴 리뉴얼 : 블로그 참조하여 풀었습니다.
- 나머지 문제는 스프링 강의 듣는다고 풀지 못했습니다.
=> 박지훈 / 4월 30일 / 1문제

cshyun7097/PGS_메뉴리뉴얼.java
컨디션이 좋지 않아 1문제밖에 풀지 못했습니다.
내일 풀어서 제출하겠습니다.
=> 최승현 / 4월 30일 / 1문제

JAEKWANG97/PGS_72411
- 메뉴 리뉴얼 : 블로그 참조
- 광고 삽입 : 시간적 여유가 없어 풀지 못했습니다.
=> 유재광 / 4월 30일 / 1문제

zzun73/PGS_72411.java
블로그 참고했습니다. 시험 대비로 1문제만 제출합니다.
=> 남혁준 / 4월 30일 / 1문제

zzun73/PGS_42578.java
=> 남혁준 / 5월 1일 / 1문제

hellomatia/PGS_42578.java
=> 이지표 / 5월 1일 / 1문제

mmalfoy/PGS_42578.java, mmalfoy/PGS_72411.java, mmalfoy/PGS_72413.java, mmalfoy/PGS_72414.java
=> 김대영 / 5월 1일 / 4문제

MJ-Kor/PGS_42578.java
Vue.js 학습 및 관통 프로젝트 준비로 1문제만 풀이했습니다.
=> 김민주 / 5월 1일 / 1문제

JAEKWANG97/PGS_42587.java, JAEKWANG97/PGS_72413.java
=> 유재광 / 5월 1일 / 2문제

mmalfoy/PGS_160585.java
=> 김대영 / 5월 2일 / 1문제

hyeonhakyi/PGS_160585.java
=> 이학현 / 5월 2일 / 1문제

minggwen/PGS_160585.java
=> 신민경 / 5월 2일 / 1문제

JiHunparkkk/PGS_160585.java, JiHunparkkk/PGS_169198.java
=> 박지훈 / 5월 2일 / 2문제

inhohyun/PGS_160585.java, inhohyun/PGS_169198.java
=> 인호현 / 5월 2일 / 2문제

zzun73/PGS_160585.java
=> 남혁준 / 5월 2일 / 1문제

hellomatia/PGS_169198.java
=> 이지표 / 5월 2일 / 1문제

inhohyun/PGS_12978.java, inhohyun/PGS_42587.java, inhohyun/PGS_42626.java
5월 3일자 못 푼 문제 2개 + 우선 주말 1문제입니다.
=> 인호현 / 5월 4일 / 3문제

hyeonhakyi/PGS_12978.java, hyeonhakyi/PGS_133500.java
=> 이학현 / 5월 4일 / 2문제

JiHunparkkk/PGS_12978.java, JiHunparkkk/PGS_133500.java
=> 박지훈 / 5월 5일 / 2문제

zzun73/PGS_12978.java
=> 남혁준 / 5월 4일 / 1문제

hellomatia/BOJ_1446.java
=> 이지표 / 5월 7일 / 1문제

hyeonhakyi/Main_1446.java, hyeonhakyi/Main_9084.java
=> 이학현 / 5월 7일 / 2문제

JAEKWANG97/BOJ_9084.java
- 하향식 DP 연습
- 나머지 한문제 금일 제출 하겠습니다.
=> 유재광 / 5월 7일 / 1문제

minggwen/BOJ_14284.java
이번주 정보처리기사 자격증 준비로 1문제만 제출하겠습니다🥲
=> 신민경 / 5월 8일 / 1문제

hyeonhakyi/BOJ_20040.java
=> 이학현 / 5월 9일 / 1문제

inhohyun/BOJ_1451.java
답안지를 참고해서 풀었습니다
관통 프로젝트 준비로 1문제만 풀었습니다...
=> 인호현 / 5월 9일 / 1문제

zzun73/BOJ_20040.java
=> 남혁준 / 5월 9일 / 1문제 

JaeHunJang/BOJ_20040.java
=> 장재훈 / 5월 9일 / 1문제

JiHunparkkk/BOJ_1451.java
=> 박지훈 / 5월 10일 / 1문제

hellomatia/BOJ_14267.java, hellomatia/BOJ_15681.java
2문제 모두 오일러 경로 테크 알고리즘을 이용하여 풀었습니다.
=> 이지표 / 5월 10일 / 2문제

hyeonhakyi/PGS_42579.java, hyeonhakyi/PGS_42627.java
=> 이학현 / 6월 3일 / 2문제

swLeesw/PGS_250136.java
solution 함수에 있는 매개변수를 전역변수로 빼도 되나요?
=> 이승원 / 6월 10일 / 1문제

minggwen/PGS_ 250136.java
여태 못 풀었던 문제 방학을 활용해서 차차 풀어나가겠습니다..!!!
=> 신민경 / 6월 10일 / 1문제

hyeonhakyi/PGS_214288.java
=> 이학현 / 6월 11일 / 1문제 

JiHunparkkk/PGS_214288.java, JiHunparkkk/PGS_250136.java
=> 박지훈 / 6월 11일 / 2문제

hellomatia/PGS_214288.java
=> 이지표 / 6월 11일 / 1문제

inhohyun/PGS_214288.java
=> 인호현 / 6월 11일 / 1문제

MJ-Kor/PGS_214288.java
=> 김민주 / 6월 11일 / 1문제

minggwen/PGS_214288.java
대기시간 계산 로직에서 시간 단축을 위해 블로그를 참고하였습니다
=> 신민경 / 6월 11일 / 1문제

hyeonhakyi/PGS_214289.java
=> 이학현 / 6월 12일 / 1문제

JaeHunJang/PGS_214289.java
=> 장재훈 / 6월 12일 / 1문제
